version: '3'
services:
  frontend:
    build:
      context: ./frontend  # This points to the folder where the Dockerfile for frontend is located
    image: multi-service-app-frontend
    ports:
      - "8080:80"
    networks:
      - my-network
  
  backend:
    build:
      context: ./backend  # This points to the folder where the Dockerfile for backend is located
    image: multi-service-app-backend
    ports:
      - "5000:5000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
